config/routes.rb
RailsBootstrap::Application.routes.draw do
  devise_for :users
  resources :users
  resources :roles
  resources :articles do
    resources :comments
  end
  root to: 'visitors#new'
end

app/models/article.rb
class Article < ActiveRecord::Base
  AVERAGE_WPM = 150.freeze

  belongs_to :pages
  has_many :comments, dependent: :destroy

  is_impressionable :counter_cache => true, :column_name => :impressions_count

  scope :published, -> { where(published: true) }
  scope :on, ->(page_id) { where(page: page_id) }
  validates :page, :title, :body, :author_name, presence: true
  validates :title, uniqueness: true

  has_attached_file :pdf, styles: {
                      thumb: ['100x100#', :jpg],
                      medium: ['300x300#', :jpg],
                      large: ['500x500#', :jpg]
                    }

  validates_attachment :pdf, content_type: {
                         content_type: 'application/pdf'
                       }

  has_attached_file :photo, styles: {
                      large: '500x500>',
                      medium: '300x300#',
                      thumb: '100x100#'
                    }

  validates_attachment_content_type :photo, content_type:
                                              ['image/jpeg',
                                               'image/png',
                                               'image/gif']

  def self.search(search)
    q = "%#{search}%"
    published.where("author_name LIKE ? OR title LIKE ?", q, q)
  end

  def page_name
    Page.find(self.page).name
  end

  def read_time
    read_time = (self.body.split.count / AVERAGE_WPM)
    if read_time >= 1
      return ("Time to read: " + read_time.to_s + " minutes")
    else
      return "Time to read: less than a minute"
    end
  end
end

app/controllers/articles_controller.rb
# controller responsible for showing articles to the user
class ArticlesController < ApplicationController
  # impressionist :actions=>[:show]

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @articles =
      if params[:search].nil?
        Article.published.
          on(params[:page_id]).
          order(created_at: :desc).
          page(params[:page]).per(10)
      else
        Article.search(params[:search])
      end
  end

  def show
    impressionist(@article)
    @comment = Comment.new(article: @article)
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)
    @article.author_name = article_params[:author_name]
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update_attributes(article_params)
        @article.author_name = article_params[:author_name]
        @article.save
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    # delete a specific article.
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title,
                                    :body,
                                    :photo,
                                    :pdf,
                                    :page,
                                    :published,
                                    :author_id,
                                    :author_name,
                                    :due_date)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.haml
.row
  - if article.photo.file?
    .col-md-2
      = link_to image_tag(article.photo.url(:thumb), class: "img-thumbnail"), article
  - elsif article.pdf.file?
    .col-md-2
      = link_to image_tag(article.pdf.url(:thumb), class: "img-thumbnail"), article
  .col-md-10
    %h3= link_to article.title, article
    %i
    %muted= "Written by: " + article.author_name + "."
    |
    %muted= "Time to read: " + article.read_time + "."
    |
    %muted= "Written: " + time_ago_in_words(article.created_at) + " ago."
    |
    - if article.comments.length.to_i > 0
      =  "Number of comments: " + article.comments.length.to_s + "."
    - else
      = "No comments yet"
%hr

app/views/articles/_author_form.html.haml
= simple_form_for(@article) do |f|
  = f.error_notification

  .form-inputs

    = f.input :page, collection: Page.all
    %section
      %header{contenteditable:"true", class:"header", id:"article_the_title"}
        Title...
      %hr
      %article{contenteditable:"true", class:"content", id:"article_content"}
        %p Body...
    = f.hidden_field :title
    = f.hidden_field :body

  .form-actions
    = f.button :submit

:javascript
  $(document).ready(function(){
    $("input[name='commit']").button().click(function(){
      $("#article_body").val($("#article_content").html());
    })
    $("input[name='commit']").button().click(function(){
      $("#article_title").val($("#article_the_title").html());
    })
    if($("#article_title").val() != ""){
      $("#article_the_title").html($("#article_title").val());
      $("#article_content").html($("#article_body").val());
    }   
  });

app/views/articles/_comment.html.haml
%p
  %hr
  %strong= comment.name + " |"
  = comment.body + " ~"
  - if can? :edit, :comment
    = # link_to "Edit", edit_article_comment_path(@article, comment)
    = link_to 'Delete', article_comment_path(@article, comment), confirm: "Are you sure?", method: :delete
  %em=  time_ago_in_words(comment.created_at) + " ago."

app/views/articles/_creative_form.html.haml
= simple_form_for(@article) do |f|
  = f.error_notification

  .form-inputs

    = f.file_field :photo
    %section
      %header{contenteditable:"false", class:"header", id:"article_the_title"}
        Title...
      %hr
      %article{contenteditable:"false", class:"content", id:"article_content"}
        %p Body...
    = f.hidden_field :title
    = f.hidden_field :body

  .form-actions
    = f.button :submit

:javascript
  $(document).ready(function(){
    $("input[name='commit']").button().click(function(){
      $("#article_body").val($("#article_content").html());
    })
    $("input[name='commit']").button().click(function(){
      $("#article_title").val($("#article_the_title").html());
    })
    if($("#article_title").val() != ""){
      $("#article_the_title").html($("#article_title").val());
      $("#article_content").html($("#article_body").val());
    }   
  });

app/views/articles/_form.html.haml
= simple_form_for(@article) do |f|
  = f.error_notification
  .col-md-12
    - if can? :edit, @article
      .form-group
        .row
          .col-md-12
            = f.input :title, input_html: { class: "form-control" }
      .form-group
        .row
          .col-md-6
            = f.input :page, collection: Page.all, input_html: { class: "form-control" }
          .col-md-6
            = f.input :author_name, :as => :string, input_html: { class: "form-control" }
      .form-group
        .row
          .col-md-6
            = f.label :photo
            = f.file_field :photo
          .col-md-6
            = f.label :pdf
            = f.file_field :pdf
      .form-group
        .row
          .col-md-12
            = f.input :body, input_html: { class: "form-control", rows: 20 }

    .form-actions
      .row
        .col-md-12
          = f.button :submit

app/views/articles/_thumb_article.html.haml
.col-md-4
  .thumbnail.myHover1.bw
    - if article.photo.file?
      = image_tag(article.photo.url(:medium))
    - elsif article.pdf.file?
      = image_tag(article.pdf.url(:medium))
    - else
      %p.text-muted.text-justify{ style: 'height:242px; overflow:hidden;' }
        = truncate(article.body, length:500)
    .caption
      %hr
      %h4= truncate(article.title, length:27)
      %i= 'by ' + article.author_name
      %p.small
        %i
          %muted= article.read_time
          %br
          %i.glyphicon.glyph.icon-calendar
          %muted= time_ago_in_words(article.created_at) + " ago"

app/views/articles/edit.html.haml
- @skip_side = true
%h1 Editing article

= render 'form'
.row
  .col-md-12
    .pull-right
      = link_to 'Show', @article
      \|
      = link_to 'Back', articles_path

app/views/articles/index.html.haml
- if @articles.length > 0
  - @articles.each do |article|
    = render article, article: article
- else
  %h1 No Articles Yet.
= paginate @articles

  

app/views/articles/new.html.haml
- @skip_side = true
%h1 New article

= render 'form'

.row
  .col-md-12
    .pull-right
      = link_to 'Back', articles_path

app/views/articles/show.html.haml
- if  !@article.photo.url.end_with?('/missing.png')
  .row
    = link_to image_tag(@article.photo.url(:large)), @article.photo.url
.row
  %h2
    = @article.title
  %p.lead
    Views
    = @article.impressions_count
    |
    = @article.read_time
    | Uploaded: 
    = @article.updated_at.month
    \-
    = @article.updated_at.day
    \-
    = @article.updated_at.year
    | By:
    %i= @article.author_name
%hr
.row
  .col-md-12
    - if  !@article.pdf.url.end_with?('/missing.png')
      .hidden-xs
        %object{height: "1100px", width: "100%", data: @article.pdf.url, type: "application/pdf"}
          %embed{height: "1100px", width: "100%", src: @article.pdf.url, type: "application/pdf"}
      .hidden-sm.hidden-md.hidden-lg
        .h1= link_to "View PDF", @article.pdf.url, :target => '_blank'
    .lead= simple_format(@article.body)
%hr

-#%h4 
  %b Share-article:

-#= image_tag("facebook.png")

-if can? :update, @article
  = link_to 'Edit', edit_article_path(@article)
  = link_to 'Delete', article_path(@article), confirm: "Are you sure?", method: :delete

%h4 Comments
- if @article.comments.length > 0
  - @article.comments.each do |comy|
    = render "comment", comment: comy
- else
  %lead Be the first to comment

= form_for([@article, @comment]) do |f|
  -if !current_user
    = link_to "Sign In", new_user_session_path
  -elsif current_user.name == nil
    = link_to "Who are you (please set a name)", current_user
  -else
    = f.text_area :body, placeholder: "Comment..."
    = f.submit

-#:javascript
  FB.ui({
    method: 'share',
    href: 'https://developers.facebook.com/docs/',
  }, function(response){});