config/routes.rb
RailsBootstrap::Application.routes.draw do
  devise_for :users
  resources :users
  resources :roles
  resources :articles do
    resources :comments
  end
  root to: 'visitors#new'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  has_and_belongs_to_many :pages

  has_attached_file :avatar,
                    styles: {
                      medium: "300x300>",
                      thumb: "100x100#",
                      icon: "50X50#"
                    },
                    default_url: "blank_profile.png"

  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
  validates :name, uniqueness: true

  before_create :setup_role

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  def self.make_all_members
    all.each do |user|
      unless user.role_ids.include?(1)
        user.role_ids = [Role.find_by_name('Member').id]
        user.save!
      end
    end
  end

  def page_name
    if self.page
      Page.find(self.page).name
    else
      ''
    end
  end

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  private

  def setup_role
    if self.role_ids.empty?
      self.role_ids = [3]
    end
  end
end

app/controllers/users_controller.rb
# Controller responsible for getting and setting things about users
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    # load the unpublished article for a particular page.
    @unpub_articles = Article.where(page: current_user.page, published: false)
    @new_articles = Article
                      .where(aasm_state: 'new', published: false)
                      .order('articles.page ASC')
    @my_articles  = Article.where(author_id: current_user)
    @my_comments = Comment.where(name: current_user.name)
    # @pub_articles = Article.where(page: current_user.page, published: true)
  end

  def new
    @user = User.new
  end

  def edit;  end

  def update # TODO shorten this.
    @user.name = params[:user][:name]
    @user.role_ids = params[:user][:role_ids]
    @user.page = params[:user][:page]
    @user.avatar = params[:user][:avatar]
    if @user.role_ids == []
      @user.role_ids = [3] # to default to member if no id
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to current_user, notice: 'user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
    # @user.update(user_params)
    # @user.role_ids = params[:user][:role_ids]
    # @user.page = params[:user][:page]
    # render text: user_params.inspect
    # redirect_to users_path
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html {
        redirect_to users_url,
                    notice: 'user was successfully deleted.'
      }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :role_ids, :page, :avatar) # try user:{:role_ids} when everyting else is working.
  end
end

app/views/users/_admin_panel.html.haml
%h3 Admin Panel
%h4
  %i
  = link_to "Manage Users", users_path

.row
  %h2 Week's Stats
  .col-md-2.thumbnail
    %h4.text-center Article views
    %h3.text-center= Impression.where("created_at >= ?", Time.zone.now.beginning_of_week).where(impressionable_type: 'Article').count
  .col-md-2.col-md-offset-1.thumbnail
    %h4.text-center Hits
    %h3.text-center
      = Impression.where("created_at >= ?", Time.zone.now.beginning_of_week).where(impressionable_type: 'Visitor').count
  .col-md-2.col-md-offset-1.thumbnail
    %h4.text-center Active Users
    %h3.text-center= User.where("last_sign_in_at >= ?", Time.zone.now.beginning_of_week).count
  .col-md-2.col-md-offset-1.thumbnail
    %h4.text-center New Articles
    %h3.text-center= Article.published.where("created_at >= ?", Time.zone.now.beginning_of_week).count
.row
  %h2 All-Time Stats
  .col-md-2.thumbnail
    %h4.text-center Article views
    %h3.text-center= Impression.where(impressionable_type: 'Article').count
  .col-md-2.col-md-offset-1.thumbnail
    %h4.text-center Hits
    %h3.text-center
      = Impression.where(impressionable_type: 'Visitor').count
  .col-md-2.col-md-offset-1.thumbnail
    %h4.text-center Users
    %h3.text-center= User.count
  .col-md-2.col-md-offset-1.thumbnail
    %h4.text-center Total Articles
    %h3.text-center= Article.published.count
%h2 All Unpublished Articles:
%table{:class => "table table-hover"}
  %thead
    %tr
      %th
        %strong Title
      %th
        %strong Page
      %th
        %strong Updated At
      = # %th
      = # %strong decision
      - Article.where(published: false).each do |article|
        %tr
          %td= link_to simple_format(article.title), edit_article_path(article)
          %td= article.page_name
          %td= article.updated_at.in_time_zone("Pacific Time (US & Canada)").strftime(" %B %d, %l:%M %p")
          %td
            = # .span.badge approve?
            = # .span.badge delete

%h2 All Editors
%table{:class => "table table-hover"}
  %thread
    %tr
      %th
        %strong Name
      %th 
        %strong Email
      - User.includes(:roles).where('roles.id'=>[4]).each do |editor|
        %tr
          %td= editor.name
          %td= editor.email
          %td

app/views/users/_author_panel.html.haml
%h3 My Articles
%table{:class => "table table-hover"}
  %thead
    %tr
      %th
        %strong title
      %th
        %strong Updated At
      %th
        = # %strong status
      - @my_articles.each do |article|
        %tr
          %td= link_to  simple_format(article.title), edit_article_path(article)
          %td= article.updated_at.in_time_zone("Pacific Time (US & Canada)").strftime(" %B %d, %l:%M %p")

app/views/users/_creative_panel.html.haml
%h3= "Creative Panel"
%table{:class => "table table-hover"}
  %thead
    %tr
      %th
        %strong title
      %th
        %strong Due
      %th
        %strong Updated At
      %th
        = # %strong Need
      - @my_articles.each do |article|
        %tr
          %td= link_to  simple_format(article.title), edit_article_path(article)
          %td SOON
          %td= article.updated_at.in_time_zone("Pacific Time (US & Canada)").strftime(" %B %d, %l:%M %p")
          %td
            = # .span.badge Upload

app/views/users/_editor_panel.html.haml
%h3= current_user.page_name + " Editor Panel"
.row
  .col-md-2
    %a.btn.btn-primary{href: new_article_path}New Article
%h3
  UNPUBLISHED ARTICLES:
%table{:class => "table table-hover"}
  %thead
    %tr
      %th
        %strong Title
      %th
        %strong Author
      %th
        %strong Updated At
      %th
        = # %strong Stage
      - @unpub_articles.each do |article|
        %tr
          %td= link_to  simple_format(article.title), edit_article_path(article)
          - if User.exists?(article.author_id)
            %td= User.find(article.author_id).name
          - else
            %td NA
          %td= article.updated_at.in_time_zone("Pacific Time (US & Canada)").strftime(" %B %d, %l:%M %p")
          %td
            = # .span.badge= article.aasm_state

%h3= current_user.page_name + " Writers Panel"

- User.where(page: current_user.page).each do |writer|
  %span.label.label-default= writer.name

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.input :name, placeholder: "name..."
  %h4 Change Profile Picture
  = f.file_field :avatar # removed until implemented with strongparams
  %h4 Assign Pages
  %p= # f.collection_check_boxes :page, Page.all, :id, :name

  - if can? :manage, :all
    %p= f.input :page, collection: Page.all, include_blank: "None", default: current_user.page
    %h4 Change Roles
    %p= f.collection_check_boxes :role_ids, Role.all, :id, :name
  - else
    - if can? :create, Article
      %h4 Hire
      %p= f.collection_check_boxes :role_ids, Role.where(id: 2..3), :id, :name
  = f.button :submit

app/views/users/_member_panel.html.haml
%h3 My Comments
%table{:class => "table table-hover"}
  %thead
    %tr
      %th
        %strong Article
        %th
          %strong Comment
          %th
            %strong Created At
            - @my_comments.each do |comment|
              %tr
                %td= link_to simple_format(Article.find(comment.article_id).title), Article.find(comment.article_id)
                %td= comment.body
                %td= comment.created_at.in_time_zone("Pacific Time (US & Canada)").strftime(" %B %d, %l:%M %p")

app/views/users/edit.html.haml
%h2= @user.email
%h5= link_to "Change Password", edit_user_registration_path
- @user.roles.each do |role|
  %i.icon-ok
  = role.name
  %hr
= render 'form'

app/views/users/index.html.haml
- if can? :manage, :all
  - @users.each do |user|
    .row
      .col-md-12
        - if user.avatar.url != "blank_profile.png"
          = image_tag user.avatar.url(:thumb)
        - else 
          = image_tag "blank_profile_thumb.png"
        .btn-group
          %button.btn.btn-default
            = link_to user_path(user) do
              %i.glyphicon.glyphicon-user
              = user.name
                      
          %button.btn.btn-default
            = link_to edit_user_path(user) do
              %i.glyphicon.glyphicon-edit
              Edit
          %button.btn.btn-default
            = link_to user, method: :delete, class: :destroy, confirm: "Are you sure?" do
              %i.glyphicon.glyphicon-trash
              Delete

app/views/users/show.html.haml
.row
  .col-md-4= image_tag @user.avatar.url(:medium), class: 'img-thumbnail'
  .col-md-8
    %h2= @user.email
    %h4= @user.name
    %h5= link_to "Change Password", edit_user_registration_path
    %p
      = 'signed in: ' + @user.sign_in_count.to_s + ' times.'
.row
  .col-md-12
    - if current_user.id == @user.id
      - current_user.roles.each do |role|
        - if role.name == "Admin"
          = render 'admin_panel'
        - elsif role.name == "Editor"
          = render 'editor_panel'
        - elsif role.name == "Author"
          = render 'author_panel'
        - elsif role.name == "Creative"
          = render 'creative_panel'
        - elsif role.name == "Member"
          = render 'member_panel'